### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by hammadzafar05** [a2insights/filament-saas-template#37]
The following link is given in the readme file which is not working

"This command will install the filament-saas app. You can find the implementation details of this command [here]"(https://github.com/a2insights/filament-saas-core/blob/main/src/Console/FilamentAdminInstallCommand.php).

**Comment by a21ns1g4ts** [comment]
streamline the development of my client projects. Initially, I used pure Laravel with HTML, then moved to Material Admin, followed by Laravel Jetstream, and currently, I'm using Filament.

My time is very limited, so I haven’t publicized this code much. The project's goal is ambitious, and I don’t have a large network to help with documentation or policy establishment. However, anyone interested in contributing or understanding how it works is welcome to explore everything here.

The application is a complete solution for a SaaS system, with a website and dashboard built with Filament. I'm still refining the billing experience using Stripe, but the integration is functional and processes payments. There's still a long road ahead, but it already helps me significantly. I can launch complex features in minimal time, and every day I work to improve it further.

This code may never gain widespread attention since I lack the time for writing documentation or the fluency in English to explain it through videos, so it may remain a hidden gem in the open-source universe.

**Comment by a21ns1g4ts** [comment]
#45 See
